### ISSUE TITLE
[tracking] endomoat feature parity with lavamoat-node

### ISSUE THREAD

**Issue by naugtur** [LavaMoat/lavamoat#1168]
1. Can run from CLI with matching options
- [x] $0 app.js
- [x] --policy and override
- [x] policy generation --autopolicy
- [x] --projectRoot (may need rethinking)
- [x] debug (may need rethinking)
- [ ] stats (WHAT IS THIS THING AND WHAT DOES IT DO???)

2. Name: 
- `@lavamoat/run`
- `lavamoat-run`
- `@lavamoat/node`
- other?

3. Features to achieve parity (provide ESM support with all these)
- [x] runs an app, handles require of dependencies
- [x] supports builtins
- [x] enforces policy on dependencies
- [x] enforces policy on builtins
- [x] supports attenuation of builtins
- [x] generates policy
- [x] supports policy-override
- [x] supports passing globals
- [x] attenuates globals recursively according to policy
- [x] supports `"write"` for globals (without nesting) AKA global store
- [x] supports dynamic require ~~(only if stated in the policy)~~
- [x] supports node native modules 
- [x] ~~supports running a package outside the lockdown realm (sass case) -- explicitly-defined "exit modules" which can be packages. look at `module` option? see how we do this currently (vm).  put the final result of that into `module` and compartment-mapper _should_ just use it~~ no longer needed
- [ ] #1527

**Comment by boneskull** [comment]
@naugtur The flags for `endomoat` are not identical (and IMO they should not be identical), but the functionality is there.

**Comment by boneskull** [comment]
The remaining item here looks like "scuttling". I'm going to create a new issue for that and close this one out.
