### ISSUE TITLE
[tracking] webpack plugin feature checklist

### ISSUE THREAD

**Issue by naugtur** [LavaMoat/lavamoat#1170]
- [x] build bundles with lavamoat
- [x] generate policy in webpack compilation
- [x] enforce package policy at runtime
- [x] enforce and attenuate globals at runtime
- [x] support `"write"` for globals AKA global store
- [x] support builtins (for node.js target in webpack build)
- [x] support inlining lockdown into the bundle
- [ ] support webpack aliases
- [ ] more?
